"""Text templates for ``cascade new``.

Written as commented text rather than generated with ``yaml.safe_dump``: a
skeleton's job is to teach the shape of the file, and comments are how it does
that — a dumper would strip them. The cost is that these are not guaranteed
loadable by construction, so ``tests/test_cli.py`` asserts that each scaffolded
file round-trips through its real loader.

``cascade.toml`` is *not* templated here: it is generated by ``Project.dump()``,
which keeps the one writer for that file in the project module.
"""


PIPELINE_SKELETON = """\
# The pipeline: what to run, and how the pieces connect.
#
# This is a skeleton — the root keys are present but empty, so `cascade validate`
# will report findings until you define at least one ref and a dag for the
# entrypoint to name. That is expected.

entrypoint: main

# Inputs supplied at run time, addressed inside dags as `$input`.
input: []
#  - { name: image, type: "io.Image" }

# Named structures usable as port types. `extends` gives single inheritance.
types:
  structures: []
#    - name: Detection
#      fields:
#        - { name: label,      type: "string" }
#        - { name: confidence, type: "float" }

# Refs: the runnable units. Each declares a runner, its config, and typed ports.
refs: []
#  - name: detect
#    runner: docker          # docker | subprocess | echo
#    config: { image: "my-registry/detect:v1" }
#    input:  [ { name: image, type: "io.Image" } ]
#    output: [ { name: dets,  type: "Detection[]" } ]

# Dags: how refs (and other dags) compose. `scatter` fans a list out over a node;
# a dag's `output` wires its results back onto its own ports.
dags: []
#  - name: main
#    input: [ { name: image, type: "io.Image" } ]
#    nodes:
#      - name: d
#        runs: detect
#        depends_on: [ { node: "$input", field: image, as: image } ]
#    output: [ { node: d, field: dets, as: dets } ]
"""

DEPLOYMENT_SKELETON = """\
# The deployment: what this project runs *on*.
#
# Kept separate from cascade.toml so the same project can target different
# substrates — a local directory in development, a bucket in production —
# without its identity changing. Point at another file with --deployment.

name: local

# Where data lives. The base scope is part of this binding, not of the project.
store:
  kind: file                # file | s3
  config:
    root: ./_store
    scope: []               # e.g. [wilder, moth] — prefixes every key
#
# The s3 equivalent:
# store:
#   kind: s3
#   config:
#     bucket: my-bucket
#     prefix: cascade
#     region: eu-west-1
#     scope: []

# Deployment-level defaults per runner kind, merged under each ref's own config.
runners: {}
#  docker:
#    no_pull: true           # use a locally built image
#    memory: 2048
"""
