import json
from dataclasses import dataclass, field

from cascade.store.base import Store
from cascade.store.registry import encode


@dataclass
class RunSpec:
    name: str
    run_id: str  # generated by the engine
    node_id: str | None = None  # generated by the dag
    instance_id: str | None = None
    store: Store | None = None
    env: dict[str, str] = field(default_factory=dict)


def to_env(spec: RunSpec) -> dict[str, str]:
    env = dict(spec.env)
    if spec.store:
        env["CASCADE_STORE_CONF"] = json.dumps(encode(spec.store))
    env["CASCADE_RUN_SPEC"] = json.dumps(
        {
            "name": spec.name,
            "run_id": spec.run_id,
            "node_id": spec.node_id,
            "instance_id": spec.instance_id,
        }
    )
    return env
