"""``RunSpec`` — everything handed to one spawn, and its env projection.

The spec carries four kinds of thing: *identity* (run, node, instance), *stores*,
*input bindings*, and *args*. There is no output binding: output ports live in the
plan's ``Signature`` and their location is already fixed by ``store_out``'s scope.

The env projection is the wire format for containers; an in-process runner reads the
spec directly instead.

**Two stores, not one.** ``store_in`` is scoped to the parent dag, so an instance
can read its siblings' outputs without anything being copied; ``store_out`` is
scoped to the instance's own slot, so it cannot write outside it. That asymmetry is
what makes containment structural rather than a convention the container is trusted
to honour — the executor sees the whole tree, an instance sees its own slot plus
read access to its dag.
"""
import json
from dataclasses import dataclass, field
from typing import Any

from cascade.store.base import Store
from cascade.store.registry import encode

from cascade.engine.binding import InputBindings


@dataclass
class RunSpec:
    name: str
    run_id: str  # generated by the engine
    node_id: str | None = None  # generated by the dag
    instance_id: str | None = None
    store_in: Store | None = None  # dag-scoped: sibling outputs are visible
    store_out: Store | None = None  # instance-scoped: this slot only
    inputs: InputBindings | None = None
    args: dict[str, Any] = field(default_factory=dict)
    env: dict[str, str] = field(default_factory=dict)


def to_env(spec: RunSpec) -> dict[str, str]:
    env = dict(spec.env)
    if spec.store_in:
        env["CASCADE_STORE_IN"] = json.dumps(encode(spec.store_in))
    if spec.store_out:
        env["CASCADE_STORE_OUT"] = json.dumps(encode(spec.store_out))
    if spec.inputs is not None:
        env["CASCADE_INPUTS"] = json.dumps(spec.inputs.encode())
    if spec.args:
        env["CASCADE_ARGS"] = json.dumps(spec.args)
    env["CASCADE_RUN_SPEC"] = json.dumps(
        {
            "name": spec.name,
            "run_id": spec.run_id,
            "node_id": spec.node_id,
            "instance_id": spec.instance_id,
        }
    )
    return env